[package]
name = "hash40"
description = "library for working with Hash40 types in Smash Ultimate"
repository = "https://github.com/BenHall-7/hash40-rs"
license = "MIT"
version = "0.1.0"
authors = ["BenHall-7 <benjaminjahall@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "^1.3.2"
lazy_static = "^1.4.0"
serde = "^1.0.98"