[package]
name = "hash40"
description = "Library for working with Hash40 types in Smash Ultimate"
repository = "https://github.com/BenHall-7/hash40-rs"
license = "MIT"
version = "1.0.0"
authors = ["BenHall-7 <benjaminjahall@gmail.com>"]
edition = "2018"

[dependencies]
bimap = "0.4"
byteorder = "1.3"
crc = "2.1"
diff-struct = "0.3"
lazy_static = "1.4"
serde = "1"